services:
  - type: web
    name: evone-internal
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_JWT_SECRET
        sync: false
      - key: DOCUSEAL_API_KEY
        sync: false
      - key: TEMPLATE_ID_FORM_A_1P
        sync: false
      - key: TEMPLATE_ID_FORM_A_2P
        sync: false
      - key: TEMPLATE_ID_FORM_D_2P
        sync: false
      - key: TEMPLATE_ID_FORM_D_3P
        sync: false
      - key: TEMPLATE_ID_FORM_1_2P
        sync: false
      - key: TEMPLATE_ID_FORM_1_3P
        sync: false
